### PR TITLE
Configurable web_app location

### PR DESCRIPTION
**Pull request by emilingerslev**
Added a new configuration :web_app which determines where the node files should be located. It defaults to "web" and I've tested it works with "webapp" in the [reaxt-phoenix-example](https://github.com/ingerslevio/reaxt-phoenix-example).

I've also added a validation mix task as an attempt to make it easier to get started with reaxt.
It validates:

* `:otp_app` is configured
* `package.json` exists in the chosen `:web_app` directory
* `package.json` contains a dependency to webpack
* `reaxt_webpack` compiler is configured (only run if reaxt.validate is run)

The validation task is run during the compilation, since most of these issues will actually make the compilation explode or not work right.

### CODE REVIEW

**Comment by emilingerslev** [comment]
Just found a few improvements to the validations that I could add:

* does npm and node exists?
* webpack.config.js exists in web_app directory

What do you think of these validations? Just want to hear your input on them generally before putting more effort into them.

**Comment by emilingerslev** [comment]
@awetzel I guess you got a pretty busy schedule :smile: Can I do anything to help with this PR?

**Comment by awetzel** [comment]
Yes sorry, I have a lot of work and my coworkers are on vacation. I will
read it on Tuesday.

2015-07-30 15:11 GMT+02:00 Emil Ingerslev <notifications@github.com>:

**Comment by emilingerslev** [comment]
No problem, I know how it is. Just wanted to check if I could help in some way.

**Comment by awetzel** [comment]
I have reviewed your PR and it seems great thank you very much and sorry again for the late answer.

The "validation" feature is also a nice add in

**Comment by emilingerslev** [comment]
Great, I'm glad you liked it. If you do a 0.3.1 release, then I'll switch my project over to it.
And again, I completely understand the issue of too little time :)

**Pull request merged**
